[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"

[build]
  command = "npm install -g pnpm && pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
